export type Page = 'home' | 'learn' | 'progress' | 'lesson';
export type PatternId = 'sliding-window' | 'two-pointers' | 'binary-search' | 'prefix-sum' | 'fast-slow' | 'monotonic-stack' | 'merge-intervals' | 'graph-traversal' | 'heap-top-k' | 'backtracking' | 'dynamic-programming' | 'trie' | 'union-find' | 'topological-sort' | 'greedy' | 'bit-manipulation' | 'binary-search-answer' | 'dp-2d' | 'dijkstra' | 'kadane' | 'cyclic-sort' | 'k-way-merge' | 'matrix-traversal' | 'segment-tree' | 'fenwick-tree' | 'bellman-ford' | 'floyd-warshall' | 'kmp' | 'rabin-karp' | 'scc' | 'prim' | 'kruskal' | 'a-star' | 'sparse-table' | 'dp-optimization' | 'frequency-map' | 'linked-list-reversal' | 'tree-traversals' | 'bst' | 'lca' | 'lis' | 'knapsack' | 'lcs' | 'edit-distance' | 'coin-change' | 'difference-array' | 'sweep-line' | 'monotonic-queue' | 'quickselect' | 'dutch-flag' | 'meet-in-middle' | 'merge-sort' | 'quick-sort' | 'counting-sort' | 'z-algorithm' | 'manacher' | 'aho-corasick' | 'eulerian-path' | 'bridges' | 'zero-one-bfs' | 'multi-source-bfs' | 'tree-diameter' | 'tree-dp' | 'bitmask-dp' | 'digit-dp';

export type Frame = {
  title: string;
  explanation: string;
  values: number[];
  left?: number;
  right?: number;
  mid?: number;
  windowStart?: number;
  windowEnd?: number;
  active?: number[];
  dimmed?: number[];
  outgoing?: number;
  incoming?: number;
  metric?: string;
  codeLine: number;
  prefix?: number[];
  slow?: number;
  fast?: number;
  stack?: number[];
  queue?: number[];
  visited?: number[];
  edges?: [number, number][];
  intervals?: [number, number][];
  merged?: [number, number][];
  path?: number[];
  dp?: number[];
  labels?: string[];
  triePath?: string[];
  words?: string[];
  parents?: number[];
  indegree?: number[];
  weights?: [number, number, number][];
  distances?: number[];
  selected?: number[];
  bits?: string[];
  range?: [number, number];
  candidate?: number;
  feasible?: boolean;
  grid?: number[][];
  cell?: [number, number];
  currentRange?: [number, number];
  bestRange?: [number, number];
  currentSum?: number;
  bestSum?: number;
  swap?: [number, number];
  arrays?: number[][];
  heads?: number[];
  chosen?: number;
  matrix?: number[][];
  pass?: number;
  tree?: { label: string; value: number; range: [number, number]; level: number; pos: number; active?: boolean }[];
  fenwick?: number[];
  fenwickLinks?: [number, number][];
  text?: string;
  patternText?: string;
  lps?: number[];
  charWindow?: [number, number];
  hash?: string;
  components?: number[];
  selectedEdges?: [number, number][];
  heuristic?: number[];
  sparse?: number[][];
  rolling?: number[];
  frequency?: Record<string, number>;
  order?: number[];
  pivot?: number;
  deque?: number[];
  events?: { x: number; delta: number; active?: boolean }[];
  halves?: number[][];
  ancestorTable?: number[][];
  target?: number;
};

export type Pattern = {
  id: PatternId;
  no: string;
  title: string;
  subtitle: string;
  category: string;
  summary: string;
  analogyTitle: string;
  analogyBody: string;
  mapping: [string, string][];
  invariant: string;
  signals: string[];
  avoid: string[];
  complexity: { time: string; space: string };
  frames: Frame[];
  code: string[];
  quiz: {
    question: string;
    options: string[];
    correct: number;
    explanation: string;
  };
};
